baseURL: 'https://Ry1005.github.io'
title: Ryan Nguyen
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A fast, clean Hugo theme'
homepage: 'https://Ry1005.github.io'
defaultContentLanguage: 'en'
googleAnalytics: G-xxx
#paginate: 10 (depreciated)
pagination:
  disableAliases: false
  pagerSize: 10
  path: page
params:
  brand: HOME
  avatarURL: Chill-Guy.png
  author: Ryan Nguyen
  authorDescription: Aspiring Cyber Security Professional
  info: Welcome! This site is to showcase stuff about me, projects, and anything I am learning.
  favicon: Chill-Guy.png
  options:
    showDarkMode: true
    enableImgZooming: true
    #enableMultiLang: true (depreciated)
    hugo.IsMultilingual: true
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
  comments:
    giscus:
      enable: true
      repo: username/repo
      repo_id: xxx
      category: Announcements
      category_id: xxx
      mapping: pathname
      position: top
      lang: en # pick a language from https://github.com/giscus/giscus/tree/main/locales
    utteranc:
      enable: false
      repo: username/xxx
      issueTerm: pathname
  analytics:
    google:
      SiteVerificationTag: xxx
    umami:
      enable: true
      website_id: xxx
      url: https://xxx
  #guestbook: (my site does not have a guestbook)
    #title: Guestbook
    #description: Leave a comment below. It could be anything –- question, appreciation, information, or even humor.
  social:
    - name: LinkedIn
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" 
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" 
                stroke-linejoin="round" class="feather feather-linkedin">
                <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z">
                </path><rect x="2" y="9" width="4" height="12">
                </rect><circle cx="4" cy="4" r="2"></circle></svg>
      url: 'https://www.linkedin.com/in/ryannguyen2024/'
    - name: GitHub
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" 
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" 
                class="feather feather-github">
                <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 
                5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 
                1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22">
                </path></svg>
      url: 'https://github.com/Ry1005'
    - name: Email
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" 
                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" 
                stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z">
                </path><polyline points="22,6 12,13 2,6"></polyline></svg>
      url: 'mailto:ryanhnguyen1005@gmail.com'
languages:
  en:
    languageName: EN
    menu:
      main:
        - name: About
          url: /about
          weight: 1
        - name: Experience
          url: /experience
          weight: 2
        - name: Projects
          url: /projects
          weight: 4
        - name: Misc.
          url: /miscellaneous
          weight: 5
        - name: Learning
          url: /learning
          weight: 5
        
        - #name: Guestbook (left here in case I want to add more)
          #url: /guestbook
          #weight: 4
        - #name: Dashboard
          #url: https://google.com
          #weight: 5
taxonomies:
  series: series
  tag: tags
